// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: web.proto

package com.ceit.desktop.grpc.controlCenter;

public interface DevUnRegisterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:web.DevUnRegisterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string devica_mac = 2;</code>
   * @return The devicaMac.
   */
  String getDevicaMac();
  /**
   * <code>string devica_mac = 2;</code>
   * @return The bytes for devicaMac.
   */
  com.google.protobuf.ByteString
      getDevicaMacBytes();
}
